'use client';

import React from 'react';
import Navbar from '@/components/landing/Navbar';
import Footer from '@/components/landing/Footer';
import { FileText, CheckCircle2 } from 'lucide-react';

export default function TermsOfUsePage() {
  return (
    <div className="min-h-screen flex flex-col bg-background text-foreground">
      <Navbar />
      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 py-32 space-y-8">
        <div className="space-y-3">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold text-blue-500 bg-blue-500/10 border border-blue-500/20">
            <FileText className="w-3.5 h-3.5" />
            <span>EchoGPT Legal Terms</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-black text-foreground">Terms of Service</h1>
          <p className="text-xs text-muted-foreground">Last updated: September 27, 2026</p>
        </div>

        <div className="prose dark:prose-invert max-w-none text-xs sm:text-sm text-muted-foreground space-y-6 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-base font-bold text-foreground">1. Acceptance of Terms</h2>
            <p>By accessing or utilizing the EchoGPT web application or Chrome Extension, you agree to comply with and be bound by these Terms of Service.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-foreground">2. Usage Rights & Output Ownership</h2>
            <p>You retain 100% full intellectual property ownership of all output, code, and content generated by AI models through your EchoGPT account.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-foreground">3. Fair Use & Subscription Billing</h2>
            <p>Pro subscriptions are billed on a recurring monthly or annual basis as selected during checkout. You can cancel at any time with no fees.</p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
